version: '3'
services:
  web:
    build: 
      context: ./web
    ports:
      - 3000:3000
  todoapp:
    build:
      context: ./todoapp
    ports:
      - 5000:5000
    depends_on:
      - mssql
  weatherapi:
    build: 
      context: ./weatherapi
    ports:
      - 5000:5000
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - todoapp
      - weatherapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      